# Generated by Django 5.0.2 on 2024-02-21 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ishuga', '0003_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insert_students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.RemoveField(
            model_name='school',
            name='Location',
        ),
    ]
