# Generated by Django 5.0.2 on 2024-02-28 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ishuga', '0004_insert_students_remove_school_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Insert_students',
        ),
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='images/'),
        ),
    ]
